# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Summary
    url: /#bio
    weight: 10
  - name: Projects
    url: /#projects
    weight: 50
  - name: News
    url: /#news
    weight: 40
  - name: Publications
    url: /#papers
    weight: 20
  - name: Bio
    url: /#experience
    weight: 30


